steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '-f'
      - 'apps/web/Dockerfile' # Explicitly specify the Dockerfile to use
      - '.'
    # The build will now run from the root of the project, giving it access to the entire monorepo

  # 2. Push the container image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

  # 3. Deploy container image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Makes the service publicly accessible
      - '--quiet' # Suppresses interactive prompts

# Store the image name for later use
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

# Define user-substitutable variables with default values.
# You can override these in your Cloud Build trigger settings.
substitutions:
  _SERVICE_NAME: 'sabq2025cloud-github-trigger'
  _REGION: 'us-central1'
  _REPO_NAME: 'sabq2025cloud'

options:
  logging: CLOUD_LOGGING_ONLY
