# This is a simplified file for debugging the build process.
steps:
  # Step 0: Copy source to a clean directory, excluding node_modules to avoid symlink issues.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - "echo '--- Step 0: Copying source code to /tmp/source ---' && mkdir /tmp/source && rsync -a --exclude '**/node_modules' --exclude '.git' . /tmp/source && echo '--- Step 0: Source code copied successfully. ---'"

  # Step 1: Build the web container image from the clean source directory.
  - name: 'gcr.io/cloud-builders/docker'
    dir: '/tmp/source/apps/web' # Run this step inside the web app's directory.
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/web:${_TAG}'
      - '-f'
      - 'Dockerfile'
      - '../..' # The build context is the root of the clean source directory.

substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'sabq2025cloud'
  _TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
