version: '3.8'
services:
  db:
    image: postgres:15
    container_name: sabq_db
    restart: always
    environment:
      POSTGRES_DB: sabq_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: sabq_web
    ports:
      - '3000:3000'
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: sabq_api
    ports:
      - '3001:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/sabq_db

volumes:
  postgres_data:
